require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');
const User = require('./models/User');
const connectDB = require('./config/db');

const sampleProducts = [
  // SHIRTS
  {
    name: "Iron Man Arc Reactor Premium T-Shirt",
    description: "Feel the power of Tony Stark's genius with this premium arc reactor design t-shirt. Features a glowing arc reactor graphic that shines in the dark. Made from 100% premium cotton.",
    price: 29.99,
    originalPrice: 39.99,
    category: "shirts",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-shirt.jpg", publicId: "iron-man-shirt" }],
    stock: 100,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Red", hex: "#E23636" }],
    rating: 4.8,
    numReviews: 245,
    featured: true,
  },
  {
    name: "Spider-Man Web Slinger T-Shirt",
    description: "Swing into action with this amazing Spider-Man t-shirt featuring the classic web pattern design. Perfect for your friendly neighborhood hero!",
    price: 24.99,
    originalPrice: 34.99,
    category: "shirts",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-shirt.jpg", publicId: "spiderman-shirt" }],
    stock: 150,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Red", hex: "#E23636" }, { name: "Blue", hex: "#006BB3" }],
    rating: 4.9,
    numReviews: 389,
    featured: true,
  },
  {
    name: "Captain America Shield T-Shirt",
    description: "Represent the First Avenger with this vintage-style Captain America shield t-shirt. Made with premium quality fabric for ultimate comfort.",
    price: 27.99,
    originalPrice: 35.99,
    category: "shirts",
    character: "captain-america",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/cap-shirt.jpg", publicId: "cap-shirt" }],
    stock: 120,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Blue", hex: "#006BB3" }, { name: "White", hex: "#FFFFFF" }],
    rating: 4.7,
    numReviews: 178,
    featured: true,
  },
  {
    name: "Thor Mjolnir Lightning T-Shirt",
    description: "Channel the God of Thunder with this epic Mjolnir design featuring lightning effects. Whosoever wears this shirt, if they be worthy...",
    price: 26.99,
    category: "shirts",
    character: "thor",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/thor-shirt.jpg", publicId: "thor-shirt" }],
    stock: 90,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#1A1A2E" }, { name: "Silver", hex: "#C0C0C0" }],
    rating: 4.6,
    numReviews: 156,
    featured: false,
  },
  {
    name: "Hulk Smash Graphic T-Shirt",
    description: "HULK SMASH! This powerful graphic tee features the Incredible Hulk in all his green glory. Warning: Shirt may cause spontaneous flexing.",
    price: 24.99,
    category: "shirts",
    character: "hulk",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/hulk-shirt.jpg", publicId: "hulk-shirt" }],
    stock: 80,
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Green", hex: "#228B22" }, { name: "Purple", hex: "#800080" }],
    rating: 4.5,
    numReviews: 134,
    featured: false,
  },
  {
    name: "Black Panther Wakanda Forever T-Shirt",
    description: "Wakanda Forever! Honor the legacy with this stunning Black Panther design featuring the Vibranium suit pattern.",
    price: 29.99,
    originalPrice: 39.99,
    category: "shirts",
    character: "black-panther",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/black-panther-shirt.jpg", publicId: "black-panther-shirt" }],
    stock: 110,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Gold", hex: "#FFD700" }],
    rating: 4.9,
    numReviews: 267,
    featured: true,
  },
  {
    name: "Avengers Assemble Team T-Shirt",
    description: "Unite Earth's Mightiest Heroes! This epic team t-shirt features all your favorite Avengers in an action-packed design.",
    price: 32.99,
    originalPrice: 42.99,
    category: "shirts",
    character: "avengers",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/avengers-shirt.jpg", publicId: "avengers-shirt" }],
    stock: 200,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Navy", hex: "#1A1A2E" }],
    rating: 4.8,
    numReviews: 456,
    featured: true,
  },
  // PANTS
  {
    name: "Spider-Man Web Pattern Joggers",
    description: "Comfortable joggers with subtle Spider-Man web pattern. Perfect for lounging or swinging through the city.",
    price: 44.99,
    originalPrice: 54.99,
    category: "pants",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-pants.jpg", publicId: "spiderman-pants" }],
    stock: 75,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#1A1A2E" }, { name: "Black", hex: "#000000" }],
    rating: 4.6,
    numReviews: 89,
    featured: false,
  },
  {
    name: "Iron Man Tech Cargo Pants",
    description: "Functional cargo pants inspired by Tony Stark's workshop gear. Multiple pockets for all your gadgets and tools.",
    price: 59.99,
    originalPrice: 79.99,
    category: "pants",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-pants.jpg", publicId: "iron-man-pants" }],
    stock: 60,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Dark Grey", hex: "#333333" }, { name: "Red", hex: "#E23636" }],
    rating: 4.4,
    numReviews: 67,
    featured: false,
  },
  {
    name: "Captain America Training Sweatpants",
    description: "Train like a super soldier with these comfortable Captain America sweatpants. Perfect for your heroic workout sessions.",
    price: 39.99,
    category: "pants",
    character: "captain-america",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/cap-pants.jpg", publicId: "cap-pants" }],
    stock: 85,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Blue", hex: "#006BB3" }, { name: "Grey", hex: "#808080" }],
    rating: 4.5,
    numReviews: 72,
    featured: false,
  },
  {
    name: "Black Panther Vibranium Weave Pants",
    description: "Sleek and stylish pants with subtle Vibranium weave pattern. Fit for Wakandan royalty.",
    price: 64.99,
    originalPrice: 84.99,
    category: "pants",
    character: "black-panther",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/black-panther-pants.jpg", publicId: "black-panther-pants" }],
    stock: 50,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.7,
    numReviews: 45,
    featured: true,
  },
  // BAGS
  {
    name: "Iron Man Suit-Up Backpack",
    description: "Premium backpack designed like Tony Stark's suit. Features arc reactor highlight and multiple compartments for laptops and gear.",
    price: 69.99,
    originalPrice: 89.99,
    category: "bags",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-bag.jpg", publicId: "iron-man-bag" }],
    stock: 45,
    sizes: ["One Size"],
    colors: [{ name: "Red & Gold", hex: "#E23636" }],
    rating: 4.9,
    numReviews: 134,
    featured: true,
  },
  {
    name: "Spider-Man Web Shooter Messenger Bag",
    description: "Stylish messenger bag with web shooter design. Perfect for carrying your daily essentials in true Spidey style.",
    price: 49.99,
    category: "bags",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-bag.jpg", publicId: "spiderman-bag" }],
    stock: 60,
    sizes: ["One Size"],
    colors: [{ name: "Red", hex: "#E23636" }, { name: "Blue", hex: "#006BB3" }],
    rating: 4.7,
    numReviews: 98,
    featured: false,
  },
  {
    name: "Captain America Shield Backpack",
    description: "Carry your gear like a true patriot with this shield-shaped Captain America backpack. Durable and iconic!",
    price: 59.99,
    category: "bags",
    character: "captain-america",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/cap-bag.jpg", publicId: "cap-bag" }],
    stock: 55,
    sizes: ["One Size"],
    colors: [{ name: "Blue & Red", hex: "#006BB3" }],
    rating: 4.8,
    numReviews: 112,
    featured: true,
  },
  {
    name: "Avengers Tactical Duffle Bag",
    description: "Large tactical duffle bag for all your mission essential gear. Features Avengers logo and multiple storage compartments.",
    price: 79.99,
    originalPrice: 99.99,
    category: "bags",
    character: "avengers",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/avengers-bag.jpg", publicId: "avengers-bag" }],
    stock: 40,
    sizes: ["One Size"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Navy", hex: "#1A1A2E" }],
    rating: 4.6,
    numReviews: 78,
    featured: false,
  },
  {
    name: "Thor Asgardian Leather Satchel",
    description: "Premium leather satchel with Norse runes and Mjolnir emblem. Worthy of carrying treasures from the nine realms.",
    price: 89.99,
    category: "bags",
    character: "thor",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/thor-bag.jpg", publicId: "thor-bag" }],
    stock: 30,
    sizes: ["One Size"],
    colors: [{ name: "Brown", hex: "#8B4513" }, { name: "Black", hex: "#000000" }],
    rating: 4.5,
    numReviews: 56,
    featured: false,
  },
  // PENS
  {
    name: "Iron Man Repulsor Pen Set",
    description: "Premium pen set designed like Iron Man's repulsor. Features LED light and premium writing experience. Set of 3 pens.",
    price: 19.99,
    originalPrice: 29.99,
    category: "pens",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-pen.jpg", publicId: "iron-man-pen" }],
    stock: 200,
    sizes: ["One Size"],
    colors: [{ name: "Red & Gold", hex: "#E23636" }],
    rating: 4.6,
    numReviews: 234,
    featured: true,
  },
  {
    name: "Spider-Man Web Fluid Gel Pens",
    description: "Write with Spidey precision! These gel pens feature web-fluid style ink and Spider-Man design. Pack of 5 pens.",
    price: 14.99,
    category: "pens",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-pen.jpg", publicId: "spiderman-pen" }],
    stock: 300,
    sizes: ["One Size"],
    colors: [{ name: "Red & Blue", hex: "#E23636" }],
    rating: 4.5,
    numReviews: 178,
    featured: false,
  },
  {
    name: "Thor Mjolnir Stylus Pen",
    description: "A pen worthy of the gods! This stylus pen is shaped like Mjolnir and works on all touchscreen devices.",
    price: 24.99,
    category: "pens",
    character: "thor",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/thor-pen.jpg", publicId: "thor-pen" }],
    stock: 150,
    sizes: ["One Size"],
    colors: [{ name: "Silver", hex: "#C0C0C0" }],
    rating: 4.8,
    numReviews: 145,
    featured: true,
  },
  {
    name: "Avengers Infinity Pen Collection",
    description: "Complete collection of 6 Infinity Stone-inspired pens. Each pen represents an Infinity Stone with matching gem color.",
    price: 34.99,
    originalPrice: 49.99,
    category: "pens",
    character: "avengers",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/avengers-pen.jpg", publicId: "avengers-pen" }],
    stock: 100,
    sizes: ["One Size"],
    colors: [{ name: "Multi", hex: "#FFD700" }],
    rating: 4.9,
    numReviews: 267,
    featured: true,
  },
  {
    name: "Hulk Smash Stress Pen",
    description: "Write away your frustrations with this Hulk-themed stress relief pen. Squeeze the grip for stress relief!",
    price: 12.99,
    category: "pens",
    character: "hulk",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/hulk-pen.jpg", publicId: "hulk-pen" }],
    stock: 250,
    sizes: ["One Size"],
    colors: [{ name: "Green", hex: "#228B22" }],
    rating: 4.3,
    numReviews: 89,
    featured: false,
  },
  // ACCESSORIES
  {
    name: "Doctor Strange Eye of Agamotto Necklace",
    description: "Replica of the Eye of Agamotto, opens and closes just like in the films. Perfect for any sorcerer supreme cosplay!",
    price: 39.99,
    originalPrice: 59.99,
    category: "accessories",
    character: "doctor-strange",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/strange-necklace.jpg", publicId: "strange-necklace" }],
    stock: 80,
    sizes: ["One Size"],
    colors: [{ name: "Gold", hex: "#FFD700" }],
    rating: 4.9,
    numReviews: 312,
    featured: true,
  },
  {
    name: "Iron Man Arc Reactor Keychain",
    description: "Miniature arc reactor keychain that actually lights up! A must-have for any Iron Man fan.",
    price: 14.99,
    category: "accessories",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-keychain.jpg", publicId: "iron-man-keychain" }],
    stock: 300,
    sizes: ["One Size"],
    colors: [{ name: "Silver & Blue", hex: "#C0C0C0" }],
    rating: 4.7,
    numReviews: 456,
    featured: false,
  },
  {
    name: "Black Widow Bite Bracelets",
    description: "Stylish bracelet set inspired by Black Widow's Widow's Bite gauntlets. Set of 2 adjustable bracelets.",
    price: 29.99,
    category: "accessories",
    character: "black-widow",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/widow-bracelet.jpg", publicId: "widow-bracelet" }],
    stock: 90,
    sizes: ["One Size"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Red", hex: "#E23636" }],
    rating: 4.6,
    numReviews: 123,
    featured: false,
  },
  // HOODIES
  {
    name: "Spider-Man Suit Hoodie",
    description: "Full-zip hoodie designed like Spider-Man's suit. Features mask hood and web pattern details.",
    price: 69.99,
    originalPrice: 89.99,
    category: "hoodies",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-hoodie.jpg", publicId: "spiderman-hoodie" }],
    stock: 70,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Red & Blue", hex: "#E23636" }],
    rating: 4.9,
    numReviews: 289,
    featured: true,
  },
  {
    name: "Iron Man Mark Armor Hoodie",
    description: "Premium hoodie with Iron Man armor design. Features metallic print and arc reactor chest detail.",
    price: 74.99,
    originalPrice: 94.99,
    category: "hoodies",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-hoodie.jpg", publicId: "iron-man-hoodie" }],
    stock: 65,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Red & Gold", hex: "#E23636" }],
    rating: 4.8,
    numReviews: 198,
    featured: true,
  },
  {
    name: "Captain America Classic Hoodie",
    description: "Classic Captain America hoodie with shield logo on the back. Perfect for showing your patriotic side.",
    price: 59.99,
    category: "hoodies",
    character: "captain-america",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/cap-hoodie.jpg", publicId: "cap-hoodie" }],
    stock: 80,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Navy", hex: "#1A1A2E" }, { name: "Royal Blue", hex: "#4169E1" }],
    rating: 4.7,
    numReviews: 167,
    featured: false,
  },
  // CAPS
  {
    name: "Spider-Man Logo Snapback Cap",
    description: "Classic snapback cap with embroidered Spider-Man logo. Adjustable strap fits all sizes.",
    price: 24.99,
    category: "caps",
    character: "spider-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/spiderman-cap.jpg", publicId: "spiderman-cap" }],
    stock: 150,
    sizes: ["One Size"],
    colors: [{ name: "Red", hex: "#E23636" }, { name: "Black", hex: "#000000" }],
    rating: 4.6,
    numReviews: 134,
    featured: false,
  },
  {
    name: "Avengers A Logo Cap",
    description: "Premium fitted cap with iconic Avengers 'A' logo. Available in multiple colors.",
    price: 27.99,
    category: "caps",
    character: "avengers",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/avengers-cap.jpg", publicId: "avengers-cap" }],
    stock: 180,
    sizes: ["One Size"],
    colors: [{ name: "Black", hex: "#000000" }, { name: "Navy", hex: "#1A1A2E" }, { name: "Red", hex: "#E23636" }],
    rating: 4.7,
    numReviews: 189,
    featured: true,
  },
  // COLLECTIBLES
  {
    name: "Iron Man Helmet Replica",
    description: "Electronic Iron Man helmet with LED eyes and voice changer. Opens and closes like the real suit!",
    price: 149.99,
    originalPrice: 199.99,
    category: "collectibles",
    character: "iron-man",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/iron-man-helmet.jpg", publicId: "iron-man-helmet" }],
    stock: 25,
    sizes: ["One Size"],
    colors: [{ name: "Red & Gold", hex: "#E23636" }],
    rating: 4.9,
    numReviews: 89,
    featured: true,
  },
  {
    name: "Captain America Shield Replica",
    description: "Metal shield replica with leather straps. Perfect display piece or cosplay accessory. 24-inch diameter.",
    price: 179.99,
    originalPrice: 229.99,
    category: "collectibles",
    character: "captain-america",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/cap-shield.jpg", publicId: "cap-shield" }],
    stock: 20,
    sizes: ["One Size"],
    colors: [{ name: "Red, White & Blue", hex: "#E23636" }],
    rating: 5.0,
    numReviews: 67,
    featured: true,
  },
  {
    name: "Infinity Gauntlet Electronic Fist",
    description: "Electronic Infinity Gauntlet with light-up Infinity Stones and sound effects. Snap responsibly!",
    price: 129.99,
    originalPrice: 169.99,
    category: "collectibles",
    character: "avengers",
    images: [{ url: "https://res.cloudinary.com/demo/image/upload/v1/marvel_store/infinity-gauntlet.jpg", publicId: "infinity-gauntlet" }],
    stock: 35,
    sizes: ["One Size"],
    colors: [{ name: "Gold", hex: "#FFD700" }],
    rating: 4.8,
    numReviews: 234,
    featured: true,
  },
];

const seedDatabase = async () => {
  try {
    await connectDB();
    
    // Clear existing data
    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');
    
    // Insert sample products
    await Product.insertMany(sampleProducts);
    console.log(`✅ Inserted ${sampleProducts.length} sample products`);
    
    // Create admin user
    const adminExists = await User.findOne({ email: 'admin@marvelstore.com' });
    if (!adminExists) {
      await User.create({
        name: 'Admin',
        email: 'admin@marvelstore.com',
        password: 'admin123',
        role: 'admin',
      });
      console.log('✅ Created admin user (admin@marvelstore.com / admin123)');
    }
    
    console.log('🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
